function summary = STDPanalysisGroupedV2(cells)

% Input structure
% First column being cell names (ie. ps20170325a)
% pre sweeps (37:56)
% post sweeps (66-146)

figures = 1;%

%Import and summarize data
counter = 1;
for i=1:length(cells(:,1))
    try
        [slope,amp,Vm,Rin,sweepTimes] = STDPanalysisV2(cells{i,1},cells{i,2},cells{i,3},cells{i,4},cells{i,5},cells{i,6},cells{i,7});
        
        %summarize pre and post values for pasting into a spreadsheet        
        summary(i,1) = mean(amp.postRaw)/mean(amp.preRaw);
        summary(i,2) = mean(slope.postRaw)/mean(slope.preRaw);
        summary(i,3) = sweepTimes.pre(end);                
        summary(i,4) = sweepTimes.pre(end)-sweepTimes.pre(1); % pre length
        summary(i,5) = sweepTimes.post(end)-sweepTimes.post(1); % post length
        summary(i,6) = mean(amp.preRaw);
        summary(i,7) = mean(amp.postRaw);
        summary(i,8) = mean(slope.preRaw);
        summary(i,9) = mean(slope.postRaw);
        summary(i,10) = abs(max([Rin.preMean Rin.postMean]));
        summary(i,11) = abs(max([Vm.preMean Vm.postMean]));
                
        normPreVm{counter,:} = Vm.preMean;
        normPostVm{counter,:} = Vm.postMean;
        
        normPreRin{counter,:} = Rin.preMean;
        normPostRin{counter,:} = Rin.postMean;
        
        normPreSlope{counter,:} = slope.preMean;
        normPostSlope{counter,:} = slope.postMean;
                
        normPreAmp{counter,:} = amp.preMean;
        normPostAmp{counter,:} = amp.postMean;

        counter = counter + 1;
                
    catch ME
        disp(['Could not analyze ' cells{i,1} ': ' ME.message]);
        summary(i,1:9) = NaN;
    end
end

mat2clip(summary);


%% Plot Summary Data

%align the cell tables right (pre) or left (post) and pad with NaNs
nz=max(cellfun(@numel,normPreVm));
normPreVm=fliplr(cell2mat(cellfun(@(x) [x,NaN(1,nz-numel(x))],normPreVm,'uni',false)));
nz=max(cellfun(@numel,normPostVm));
normPostVm=cell2mat(cellfun(@(x) [x,NaN(1,nz-numel(x))],normPostVm,'uni',false));

nz=max(cellfun(@numel,normPreRin));
normPreRin=fliplr(cell2mat(cellfun(@(x) [x,NaN(1,nz-numel(x))],normPreRin,'uni',false)));
nz=max(cellfun(@numel,normPostRin));
normPostRin=cell2mat(cellfun(@(x) [x,NaN(1,nz-numel(x))],normPostRin,'uni',false));

nz=max(cellfun(@numel,normPreAmp));
normPreAmp=fliplr(cell2mat(cellfun(@(x) [x,NaN(1,nz-numel(x))],normPreAmp,'uni',false)));
nz=max(cellfun(@numel,normPostAmp));
normPostAmp=cell2mat(cellfun(@(x) [x,NaN(1,nz-numel(x))],normPostAmp,'uni',false));

nz=max(cellfun(@numel,normPreSlope));
normPreSlope=fliplr(cell2mat(cellfun(@(x) [x,NaN(1,nz-numel(x))],normPreSlope,'uni',false)));
nz=max(cellfun(@numel,normPostSlope));
normPostSlope=cell2mat(cellfun(@(x) [x,NaN(1,nz-numel(x))],normPostSlope,'uni',false));

meanPreAmp = nanmean(normPreAmp);
meanPostAmp = nanmean(normPostAmp);
semPreAmp = nansem(normPreAmp);
semPostAmp = nansem(normPostAmp);

meanPreSlope = nanmean(normPreSlope);
meanPostSlope = nanmean(normPostSlope);
semPreSlope = nansem(normPreSlope);
semPostSlope = nansem(normPostSlope);

meanPreRin = nanmean(normPreRin);
meanPostRin = nanmean(normPostRin);
semPreRin = nansem(normPreRin);
semPostRin = nansem(normPostRin);

meanPreVm = nanmean(normPreVm);
meanPostVm = nanmean(normPostVm);
semPreVm = nansem(normPreVm);
semPostVm = nansem(normPostVm);

%% Plot out the data
figure('units','normalized','outerposition',[0.1 0.1 .8 .8]);
c1 = get(gca,'ColorOrder');
preTime = .5-length(normPreAmp(1,:)):1:-0.5;
postTime = 0.5:1:length(normPostAmp(1,:))-0.5;

%-----Amplitude-----
subplot(4,3,2:3)
hold on;
for i=1:length(normPreAmp(:,1))   
   plot(preTime,normPreAmp(i,:),'color',[.7 .7 .7]);    
   plot(postTime,normPostAmp(i,:),'color',[.7 .7 .7]); 
end
plot([preTime(1)-1 postTime(end)+1], [1 1], 'k--');
ylim([0.5 2]);
xlim([preTime(1)-1 postTime(end)+1]);
xlim([preTime(1)-1 20]);
errorbar(preTime,...
    meanPreAmp,...
    semPreAmp,...
    '-o',...
    'linewidth',1,...
    'color',c1(1,:),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',c1(1,:),...
    'MarkerSize',8,...
    'CapSize',0);
errorbar(postTime,...
    meanPostAmp,...
    semPostAmp,...
    '-o',...
    'linewidth',1,...
    'color',c1(2,:),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',c1(2,:),...
    'MarkerSize',8,...
    'CapSize',0);

%Formatting
set(gca,'fontsize',14,...
    'XMinorTick','on',...
    'YMinorTick','on',...
    'TickDir','out');

%Labels
ylabel('Norm Amplitude')
title('Amplitude')

%-----Slope-----
subplot(4,3,5:6)
hold on;
for i=1:length(normPreSlope(:,1))
   plot(preTime,normPreSlope(i,:),'color',[.7 .7 .7]); 
   plot(postTime,normPostSlope(i,:),'color',[.7 .7 .7]); 
end
plot([preTime(1)-1 postTime(end)+1], [1 1], 'k--');
ylim([0.5 2]);
xlim([preTime(1)-1 postTime(end)+1]);
xlim([preTime(1)-1 20]);

errorbar(preTime,...
    meanPreSlope,...
    semPreSlope,...
    '-o',...
    'linewidth',1,...
    'color',c1(1,:),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',c1(1,:),...
    'MarkerSize',8,...
    'CapSize',0);
errorbar(postTime,...
    meanPostSlope,...
    semPostSlope,...
    '-o',...
    'linewidth',1,...
    'color',c1(2,:),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',c1(2,:),...
    'MarkerSize',8,...
    'CapSize',0);

ylabel('Norm Slope')
title('Slope')

%Formatting
set(gca,'fontsize',14,...
    'XMinorTick','on',...
    'YMinorTick','on',...
    'TickDir','out');

%-----Vm-----
subplot(4,3,8:9)
hold on;
for i=1:length(normPreVm(:,1))
   plot(preTime,normPreVm(i,:),'color',[.7 .7 .7]); 
   plot(postTime,normPostVm(i,:),'color',[.7 .7 .7]); 
end
plot([preTime(1)-1 postTime(end)+1], [1 1], 'k--');
ylim([0.8 1.2]);
xlim([preTime(1)-1 postTime(end)+1]);
xlim([preTime(1)-1 20]);

errorbar(preTime,...
    meanPreVm,...
    semPreVm,...
    '-o',...
    'linewidth',1,...
    'color',c1(1,:),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',c1(1,:),...
    'MarkerSize',8,...
    'CapSize',0);
errorbar(postTime,...
    meanPostVm,...
    semPostVm,...
    '-o',...
    'linewidth',1,...
    'color',c1(2,:),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',c1(2,:),...
    'MarkerSize',8,...
    'CapSize',0);


ylabel('Norm Vm')
title('Membrane Potential')

%Formatting
set(gca,'fontsize',14,...
    'XMinorTick','on',...
    'YMinorTick','on',...
    'TickDir','out');

%-----Rin-----
subplot(4,3,11:12)
hold on;
for i=1:length(normPreRin(:,1))
   plot(preTime,normPreRin(i,:),'color',[.7 .7 .7]); 
   plot(postTime,normPostRin(i,:),'color',[.7 .7 .7]); 
end
plot([preTime(1)-1 postTime(end)+1], [1 1], 'k--');
ylim([0.8 1.2]);
xlim([preTime(1)-1 postTime(end)+1]);
xlim([preTime(1)-1 20]);

errorbar(preTime,...
    meanPreRin,...
    semPreRin,...
    '-o',...
    'linewidth',1,...
    'color',c1(1,:),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',c1(1,:),...
    'MarkerSize',8,...
    'CapSize',0);
errorbar(postTime,...
    meanPostRin,...
    semPostRin,...
    '-o',...
    'linewidth',1,...
    'color',c1(2,:),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',c1(2,:),...
    'MarkerSize',8,...
    'CapSize',0);

xlabel('Time (min)');
ylabel('Norm Rin')
title('Input Resistance')

%Formatting
set(gca,'fontsize',14,...
    'XMinorTick','on',...
    'YMinorTick','on',...
    'TickDir','out');

%
subplot(4,3,[1,4])
hold on;
scatter(ones(length(summary(:,1)),1),summary(:,1),...       
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',[0 0 0]);

plot([1.75 2.25],[mean(summary(:,1)) mean(summary(:,1))],'k','linewidth',2)
plot([1.95 2.05],[mean(summary(:,1))+nansem(summary(:,1)) mean(summary(:,1))+nansem(summary(:,1))],'k','linewidth',2)
plot([1.95 2.05],[mean(summary(:,1))-nansem(summary(:,1)) mean(summary(:,1))-nansem(summary(:,1))],'k','linewidth',2)
plot([2 2],[mean(summary(:,1))-nansem(summary(:,1)) mean(summary(:,1))+nansem(summary(:,1))],'k','linewidth',1.5)
plot([0 3],[1 1],'k--')

ylim([.8 2])
xlim([0 3]);
set(gca,'fontsize',16,...
    'xtick',[],...
    'YMinorTick','on',...
    'TickDir','out');
title('Norm Amplitude')


subplot(4,3,[7,10])
hold on;
scatter(ones(length(summary(:,2)),1),summary(:,2),...
    'MarkerEdgeColor',[1 1 1],...
    'MarkerFaceColor',[0 0 0]);

plot([1.75 2.25],[mean(summary(:,2)) mean(summary(:,2))],'k','linewidth',2)
plot([1.95 2.05],[mean(summary(:,2))+nansem(summary(:,2)) mean(summary(:,2))+nansem(summary(:,2))],'k','linewidth',2)
plot([1.95 2.05],[mean(summary(:,2))-nansem(summary(:,2)) mean(summary(:,2))-nansem(summary(:,2))],'k','linewidth',2)
plot([2 2],[mean(summary(:,2))-nansem(summary(:,2)) mean(summary(:,2))+nansem(summary(:,2))],'k','linewidth',1.5)
plot([0 3],[1 1],'k--')

ylim([.8 2])
xlim([0 3]);
set(gca,'fontsize',16,...
    'xtick',[],...
    'YMinorTick','on',...
    'TickDir','out');
title('Norm Slope')

