function L5classifierGUI

L5classifierUI = figure;

text_path = uicontrol('Style', 'text', ...
    'fontSize',30,...
    'FontUnits','normalized',...
    'Units','normalized',...
    'Position', [.1 .75 .4 .15],...
    'string','Path:');


edit_path = uicontrol('Style', 'edit', ...
    'fontSize',30,...
    'FontUnits','normalized',...
    'Units','normalized',...
    'Position', [.5 0.75 .4 .15],...
    'string','C:\Data\Export',...
    'Callback', @function_setPath);


text_cellName = uicontrol('Style', 'text', ...
    'fontSize',30,...
    'FontUnits','normalized',...
    'Units','normalized',...
    'Position', [.1 0.5 .4 .15],...
    'string','Cell Name:');

edit_cellName = uicontrol('Style', 'edit', ...
    'fontSize',30,...
    'FontUnits','normalized',...
    'Units','normalized',...
    'Position', [.5 .5 .4 .15],...
    'Callback', @function_setCellName);

text_cellType = uicontrol('Style', 'text', ...
    'fontSize',30,...
    'FontUnits','normalized',...
    'Units','normalized',...
    'Position', [.6 0.2 .3 .15],...
    'string','Type:');

panel_bufferType = uibuttongroup(...
    'units','normalized',...
    'position',[.1 .1 .35 .35],...
    'title','Buffer Type');


radio_EGTA = uicontrol('Style', 'radiobutton',...
    'fontSize',30,...
    'FontUnits','normalized',...
    'String', 'EGTA',...
    'Units','normalized',...
    'Position', [.1 .5 .8 .5],...
    'parent',panel_bufferType);

radio_Fluo5f = uicontrol('Style', 'radiobutton',...
    'fontSize',30,...
    'FontUnits','normalized',...
    'String', 'Fluo 5f',...
    'Units','normalized',...
    'Position', [.1 0 .8 .5],...
    'parent',panel_bufferType);

set(L5classifierUI,'Units','normalized','position',[.7 .7 .3 .3]);

    function function_setPath(source,callbackdata)
        
        pathName = get(source,'string');
        
         if exist(pathName,'dir') ~= 7
            warndlg('Invalid Path');
        end
    end


    function function_setCellName(source,callbackdata)
  

            if get(radio_EGTA,'value') == 1
                CaBuffer = 'EGTA';
            else get(radio_Fluo5f,'value') == 1
                CaBuffer = 'Fluo5'
            end
            
            root = pwd;
            try
                type = Import_and_Classify_LinescanViewer( get(source,'string'),get(edit_path,'string'),'yes',CaBuffer)
                set(text_cellType,'string',['Type: ' type]);
            catch
                cd(root);
                error('Could not classify cell');
            end
            
            
        
                        
    end
end





